language: python
sudo: required
services:
  - docker
install:
  - pip install codecov
script:
  - docker-compose up -d
  - sleep 15 && docker exec -it ng /bin/bash -c "coverage run --source='.' manage.py test"
after_success:
  #- docker exec -it ng /bin/bash -c "codecov -t $CODECOV_TOKEN"
  - sudo ls -al /proc/$(docker inspect --format {{.State.Pid}} ng)/root/code && sudo cp /proc/$(docker inspect --format {{.State.Pid}} ng)/root/code/.coverage ./ && sudo cat .coverage
  - sudo mkdir /code && sudo chmod 777 /code && sudo cp -R  /proc/$(docker inspect --format {{.State.Pid}} ng)/root/code/* /code/ && sudo cp -R  /proc/$(docker inspect --format {{.State.Pid}} ng)/root/code/.* /code/ 
  - cd /code && ls -al && codecov
