language: python
services:
  - docker
install:
  - pip install codecov
script:
  - docker-compose up -d
  - sleep 15 && docker exec -it ng /bin/bash -c "coverage run --source='.' manage.py test"
after_success:
  - mkdir codecov && ls -l /proc/$(docker inspect --format {{.State.Pid}} ng)/code && cd /proc/$(docker inspect --format {{.State.Pid}} ng)/code && codecov
