language: python
services:
  - docker
install:
  - pip install codecov
script:
  - docker-compose up -d --volume=./codecov:./
  - sleep 15 && docker exec -it ng /bin/bash -c "coverage run --source='.' manage.py test"
after_success:
  - mkdir codecov && ls -l /proc/$(docker inspect --format {{.State.Pid}} ng)/root && cd /proc/$(docker inspect --format {{.State.Pid}} ng)/root && codecov
