language: python
sudo: required
services:
  - docker
install:
  - pip install codecov
script:
  - docker-compose up -d
  - sleep 15 && docker exec -it ng /bin/bash -c "coverage run --source='.' manage.py test"
after_success:
  - sudo ls -l /proc/$(docker inspect --format {{.State.Pid}} ng)/code
  - sudo ls -al /proc/$(docker inspect --format {{.State.Pid}} ng)/root/code && sudo -c "cd /proc/$(docker inspect --format {{.State.Pid}} ng)/root/code && codecov"
