version: '2'

services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx:
    image: nginx:latest
    container_name: ngnix-ng
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/conf.d
      - static:/static
    depends_on:
      - web
  web:
    # build: .
    container_name: ng
    command:
      - echo "from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('admin', 'admin@example.com', 'password')" | python manage.py shell
      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/static
    ports:
      - "8000:8000"
    # environment:
    #   - VIRTUAL_HOST=naming-game.bordeaux.inria.fr
