version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-ng
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-data:/static
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=naming-game.bordeaux.inria.fr
  web:
    build: .
    container_name: ng
    command: bash -c "service postgresql restart && sleep 10 && bash update.sh && echo \"from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); user = User.objects.create_user('admin', 'admin@example.com', 'password'); user.save(); exit();\" | python manage.py shell && bash gunicorn_script.sh"
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static-data:/static
      - ./postgresql-data:/postgresql-data
    ports:
      - "8000:8000"

volumes:
  static-data:
    driver: local
